default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'
    hooks:
    -   id: autopep8
        exclude: ^docs/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    -   id: mypy
        exclude: ^docs/
